In [1]:
import pandas as pd

In [2]:
df = pd.read_json('train.json')

In [3]:
df

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [4]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-08-05,1754352001,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-08-05,1754352001,0.0419
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-08-05,1754352001,0.7790
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-08-05,1754352001,0.9620
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-08-05,1754352001,4.3800
...,...,...,...,...,...,...,...
XPF,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-08-05,1754352001,1.1800
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-08-05,1754352001,2.7500
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-08-05,1754352001,0.2050
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-08-05,1754352001,0.2630
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-08-05,1754352001,0.3050

In [5]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
     - -------------------------------------- 0.5/11.9 MB 1.2 MB/s eta 0:00:10
     --- ------------------------------------ 1.0/11.9 MB 1.4 MB/s eta 0:00:08
     ---- ----------------------------------- 1.3/11.9 MB 1.5 MB/s eta 0:00:07
     ------ --------------------------------- 1.8/11.9 MB 1.6 MB/s eta 0:00:07
     ------- -------------------------------- 2.1/11.9 MB 1.6 MB/s eta 0:00:07
     ------- -------------------------------- 2.4/11.9 MB 1.6 MB/s eta 0:00:07
     -------- ------------------------------- 2.6/11.9 MB 1.6 MB/s eta 0:00:06
     ---------- ----------------------------- 3.1/11.9 MB 1.6 MB/s eta 0:00:06
     ------------ --------------------------- 3.7/11.9 MB 1.7 MB/s eta 0:00:05
     ------------- -------------------------- 3.9/11.9 MB 1.7 MB/s eta 0:00:05
     --------------- ------------------------ 4.5/11.9 MB 1.7 MB/s eta 0:00:05
     ---------------- ----------------------- 5.0/11.9 MB 1.8 MB/s eta 0:00:04
     ----------------- ---------------------- 5.2/11.9 MB 1.8 MB/s eta 0:00:04
     ------------------- -------------------- 5.8/11.9 MB 1.8 MB/s eta 0:00:04
     -------------------- ------------------- 6.0/11.9 MB 1.8 MB/s eta 0:00:04
     ---------------------- ----------------- 6.6/11.9 MB 1.8 MB/s eta 0:00:03
     ----------------------- ---------------- 6.8/11.9 MB 1.8 MB/s eta 0:00:03
     ------------------------ --------------- 7.3/11.9 MB 1.8 MB/s eta 0:00:03
     -------------------------- ------------- 7.9/11.9 MB 1.8 MB/s eta 0:00:03
     --------------------------- ------------ 8.1/11.9 MB 1.8 MB/s eta 0:00:03
     ----------------------------- ---------- 8.7/11.9 MB 1.8 MB/s eta 0:00:02
     ------------------------------ --------- 9.2/11.9 MB 1.9 MB/s eta 0:00:02
     ------------------------------- -------- 9.4/11.9 MB 1.9 MB/s eta 0:00:02
     --------------------------------- ------ 10.0/11.9 MB 1.8 MB/s eta 0:00:02
     ---------------------------------- ----- 10.2/11.9 MB 1.8 MB/s eta 0:00:01
     ------------------------------------ --- 10.7/11.9 MB 1.8 MB/s eta 0:00:01
     ------------------------------------- -- 11.0/11.9 MB 1.8 MB/s eta 0:00:01
     -------------------------------------- - 11.5/11.9 MB 1.8 MB/s eta 0:00:01
     ---------------------------------------  11.8/11.9 MB 1.8 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 1.8 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (setup.py): started
  Building wheel for mysql.connector (setup.py): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp313-cp313-win_amd64.whl size=248039 sha256=eb2640e1aed92b5e12a696245bb0557cfde1c7ae5119032f0d0938dd0a0f07dd
  Stored in directory: c:\users\deepti devaiah\appdata\local\pip\cache\wheels\4e\c1\23\9423c444a75266a05275c80ebf5c6efe2368388e976b690a0f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

  DEPRECATION: Building 'mysql.connector' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'mysql.connector'. Discussion can be found at https://github.com/pypa/pip/issues/6334

In [6]:
import mysql.connector

In [8]:
conn = mysql.connector.connect(host='localhost',user='root',password='',database='world')

ProgrammingError: 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)

In [ ]:
pd.read_sql_query("SELECT * FROM city",conn)